name: Sync To Gitlab  #名字  可自定义
on:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #开源actions包
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:PaloMiku/Blog.git" # github仓库地址
          destination-repo: "git@gitlab.com:PaloMiku/Blog.git" # gitee仓库地址
